server:
  port: 8080
spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: username
    password: password
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}